### ISSUE TITLE
能否支持3连击 按键？

### ISSUE THREAD

**Issue by hongshui3000** [murphyzhao/FlexibleButton#10]
能否支持3连击 按键

**Comment by murphyzhao** [comment]
在技术上肯定是可以实现的，但我不确定它有怎么样的应用场景？你可以简单描述下吗？

**Comment by hongshui3000** [comment]
只有一个按键，功能 需要几个（单击一个功能，双击一个功能，3连击一个功能）  所以才会需要3连击

**Comment by murphyzhao** [comment]
那你可以这么用：

- 单击事件
- 双击事件
- 短按事件
- 长按事件
- 外加超长按事件

**Comment by murphyzhao** [comment]
在 Windows 上确实存在三连击、多击事件，后面有时间的时候，我会考虑如何加进去

**Comment by hongshui3000** [comment]
感谢回复

**Comment by murphyzhao** [comment]
新版本已经支持连击，可以尝试体验下 https://github.com/murphyzhao/FlexibleButton/releases/tag/2.0.0
