### ISSUE TITLE
触摸按键

### ISSUE THREAD

**Issue by slark-vali** [murphyzhao/FlexibleButton#11]
你好，请问支持触摸按键吗

**Comment by murphyzhao** [comment]
> 你好，请问支持触摸按键吗

都是按键，没啥区别

**Comment by slark-vali** [comment]
Readme 文档这句话是不是写错了
1	pressed_logic_level	是	设置按键按下的逻辑电平。1：高电平为按下状态；0：低电平为按下状态

**Comment by murphyzhao** [comment]
这个没问题。

这个 pressed_logic_level 是标识你按键按下状态的逻辑电平的。

因为有的按键默认是高电平，按下是低电平；有的是默认是低电平，按下是高电平。

所以，需要通过 pressed_logic_level 来辅助判断按键是否被按下。

**Comment by slark-vali** [comment]
我说的是ReadMe文档这里的表格说明，你这里对pressed_logic_level	的解释说明让人很困惑，
你这里仿佛在说1和0都是按下状态

序号	数据成员	是否需要用户初始化	说明
1	pressed_logic_level	是	设置按键按下的逻辑电平。1：高电平为按下状态；0：低电平为按下状态
2	event	否	用于记录当前按键的按键事件
3	status	否	用于记录当前按键的状态，按下、抬起、长按等
4	scan_cnt	否	用于记录扫描次数
5	click_cnt	否	用于记录单击次数，用于判断双击事件
6	debounce_tick	是	消抖时间，默认为 0，可以不配置，依靠扫描间隙进行消抖
7	click_start_tick	是	设置触发按键按下事件的起始 tick，有消抖效果
8	short_press_start_tick	是	设置短按事件触发的起始 tick
9	long_press_start_tick	是	设置长按事件触发的起始 tick
10	long_hold_start_tick	是	设置长按保持事件触发的起始 tick
11	usr_button_read	是	用户设备的按键引脚电平读取函数，重要
12	cb	是	设置按键事件回调，用于应用层对按键事件的分类处理
13	next	否	按键库使用单向链表串起所有的按键配置

**Comment by murphyzhao** [comment]
没有描述清除，我修改下，建议怎么改合适？

**Comment by slark-vali** [comment]
for(target = btn_head, i = 0;
        (target != NULL) && (target->usr_button_read != NULL);
        target = target->next, i ++)
    {
        keydata = keydata |
                  (target->pressed_logic_level == 1 ?
                  ((!(target->usr_button_read)()) << i) :
                  ((target->usr_button_read)() << i));
    }

我看了一下，你这个pressed_logic_level	只是作为一个 开关切换 的作用？

**Comment by slark-vali** [comment]
假如我有2个按键是高电平有效（如果引脚读到高电平着代表按下），2个按键是低电平有效（如果引脚读到是低电平则代表按下）；那我初始化的时候是不是 就得设置高电平有效的按键的  pressed_logic_level	 = 0，  设置低电平有效的按键的 pressed_logic_level = 1 呢?

**Comment by murphyzhao** [comment]
高电平有效的对应 pressed_logic_level  = 1 啊

**Comment by slark-vali** [comment]
为什么不表示pressed_logic_level =1 就代表按下状态，pressed_logic_level  = 0 代表不按下；这样子不管用户设置的的是高电平有效还是低电平有效，用户只需要在usr_button_read()返回 pressed_logic_level 的值就可以；我只需要在底层函数处理 pressed_logic_level 的数据就行，而不用去管用户在板子上是怎么设计的

**Comment by slark-vali** [comment]
为什么不表示pressed_logic_level =1 就代表按下状态，pressed_logic_level  = 0 代表不按下；这样子不管用户设置的的是高电平有效还是低电平有效，用户只需要在usr_button_read()返回 pressed_logic_level 的值就可以；我只需要在底层函数处理 pressed_logic_level 的数据就行，而不用去管用户在板子上是怎么设计的

**Comment by murphyzhao** [comment]
你不告诉我，我怎么只是什么电平代表按下啊？ pressed_logic_level  这个 flag 就是让你告诉底层的

**Comment by slark-vali** [comment]
User_Button[USER_BUTTON_0].usr_button_read = User_Button_0_Read;
User_Button[USER_BUTTON_1].usr_button_read = User_Button_1_Read;
用户::uint8_t User_Button_0_Read()  //高电平有效
{
     if(1 == Read(Key1_PORT,Key1_PIN))
            return User_Button[USER_BUTTON_0] . pressed_logic_level = 1;
    else
            return User_Button[USER_BUTTON_0] . pressed_logic_level = 0;
}

用户::uint8_t User_Button_1_Read()    //低电平有效
{
     if(0 == Read(Key1_PORT,Key1_PIN))
            return User_Button[USER_BUTTON_1] . pressed_logic_level = 1;
     else
            return User_Button[USER_BUTTON_1] . pressed_logic_level = 0;
}

库::flex_button_read()
{
for(target = btn_head, i = 0;
    (target != NULL) && (target->usr_button_read != NULL);
    target = target->next, i ++)
{
    keydata = keydata |
              (target->pressed_logic_level == 1 ?
              ((!(target->usr_button_read)()) << i) :
              ((target->usr_button_read)() << i));
}
}

**Comment by slark-vali** [comment]
User_Button[USER_BUTTON_0].usr_button_read = User_Button_0_Read;
User_Button[USER_BUTTON_1].usr_button_read = User_Button_1_Read;
用户::uint8_t User_Button_0_Read() //高电平有效
{
if(1 == Read(Key1_PORT,Key1_PIN))
return User_Button[USER_BUTTON_0] . pressed_logic_level = 1;
else
return User_Button[USER_BUTTON_0] . pressed_logic_level = 0;
}

用户::uint8_t User_Button_1_Read() //低电平有效
{
if(0 == Read(Key1_PORT,Key1_PIN))
return User_Button[USER_BUTTON_1] . pressed_logic_level = 1;
else
return User_Button[USER_BUTTON_1] . pressed_logic_level = 0;
}

库::flex_button_read()
{
for(target = btn_head, i = 0;
(target != NULL) && (target->usr_button_read != NULL);
target = target->next, i ++)
{
keydata = keydata | (target->usr_button_read()) << i)
}
}

**Comment by murphyzhao** [comment]
新版本更新了 README，希望已经描述清楚了该问题，感谢提出疑问。

https://github.com/murphyzhao/FlexibleButton/releases/tag/2.0.0
