### ISSUE TITLE
中断方式检测按键

### ISSUE THREAD

**Issue by Jackistang** [murphyzhao/FlexibleButton#13]
我用的是STM32F103芯片裸机编程，目前在使用该库进行中断方式检测按键出现了问题，请求大家的帮助。问题如下：

- 我已成功地配置了按键的外部中断，并且每次按下按键后会进入中断处理函数

- 我试过在中断处理函数里释放一个信号量，在main函数的while循环里检测到该信号量后调用flex_button_scan()函数，能够正常识别 “FLEX_BTN_PRESS_CLICK” 和点击 “FLEX_BTN_PRESS_DOUBLE_CLICK” 。

- 但是由于按一下按键才会调用扫描函数，当我试图触发 “FLEX_BTN_PRESS_SHORT_START” 和 “FLEX_BTN_PRESS_LONG_START” 事件时，我长按按键，这只触发一次中断，只调用一次flex_button_scan()函数，只产生了 “FLEX_BTN_PRESS_DOWN” 事件。

- 请问有什么办法实现么？

**Comment by murphyzhao** [comment]
@Jackistang 
调用 flex_button_scan 的条件：

- 中断信号

退出 flex_button_scan 的条件：

- 检测到按键 UP
- 扫描超时

**Comment by Jackistang** [comment]
多谢，成功解决了我的问题。
