### ISSUE TITLE
关于按键ID

### ISSUE THREAD

**Issue by nnqtdf** [murphyzhao/FlexibleButton#14]
最新版好像回调事件里的按键id和注册时的顺序是反的？

**Comment by murphyzhao** [comment]
按键 ID 是新版本增加的，为了多个按键使用同一个 callback 的时候区分按键，这个是跟注册顺序没有关系，是用户自行填写的，可以参考 https://github.com/murphyzhao/FlexibleButton/blob/master/flexible_button_demo.c 这个例程。

**Comment by nnqtdf** [comment]
感谢来信：
&nbsp; &nbsp; &nbsp;如图：我测试最新版，读取电平回调函数里按钮id与事件回调函数里的id是相反的。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Murphy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 上午10:27
收件人:&nbsp;"murphyzhao/FlexibleButton"<FlexibleButton@noreply.github.com&gt;;
抄送:&nbsp;"那年秋天的风"<nnqtdf@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [murphyzhao/FlexibleButton] 关于按键ID (#14)




按键 ID 是新版本增加的，为了多个按键使用同一个 callback 的时候区分按键，这个是跟注册顺序没有关系，是用户自行填写的，可以参考 https://github.com/murphyzhao/FlexibleButton/blob/master/flexible_button_demo.c 这个例程。

**Comment by murphyzhao** [comment]
@nnqtdf 
你发过来的图片没有正确展示，麻烦加我 QQ 95530056，我们确定下问题，谢谢。

**Comment by nnqtdf** [comment]
好的，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Murphy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 上午10:43
收件人:&nbsp;"murphyzhao/FlexibleButton"<FlexibleButton@noreply.github.com&gt;;
抄送:&nbsp;"那年秋天的风"<nnqtdf@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [murphyzhao/FlexibleButton] 关于按键ID (#14)




@nnqtdf
 你发过来的图片没有正确展示，麻烦加我 QQ 95530056，我们确定下问题，谢谢。
