### ISSUE TITLE
非常不合理的设计：短按事件和长按事件相关联

### ISSUE THREAD

**Issue by lulipro** [murphyzhao/FlexibleButton#27]
假设一个按键，我既要使用其短按事件，又要使用其长按事件，则应该短按时只触发短按事件，长按时只触发长按事件。然而目前的设计是：长按过程中会触发一次短按事件，我觉得这是非常不合理的！！！

**Comment by XiaoLanQi** [comment]
长按时，只会触发FLEX_BTN_PRESS_SHORT_START事件，而不会触发FLEX_BTN_PRESS_SHORT_UP事件，所以应该用FLEX_BTN_PRESS_SHORT_UP事件来用在短按完成标志，这样长按时就不会触发短按事件了，作者还是考虑到这点了。

**Comment by lulipro** [comment]
个人理解问题，已解决
