### ISSUE TITLE
关于按键连续触发事件

### ISSUE THREAD

**Issue by 1359450511** [murphyzhao/FlexibleButton#8]
你好，请问一下这个怎么改一下增加按键的连续触发，这个在调时钟的时候很方便

**Comment by murphyzhao** [comment]
你是想在按键按下的时候每隔一段时间就触发一个按下事件吗？

**Comment by 1359450511** [comment]
对的，有办法解决么 你比如说调时钟的时候 我如果按一下抬起一下，这个时候就触发一下，如果我按下超过了长按的时间就让他一直触发，这样我可以连续加减

**Comment by murphyzhao** [comment]
> 对的，有办法解决么 你比如说调时钟的时候 我如果按一下抬起一下，这个时候就触发一下，如果我按下超过了长按的时间就让他一直触发，这样我可以连续加减

嗯，明白了，今天晚些时候我看看如何增加该功能，你也可以尝试下 :simple_smile: 。

**Comment by murphyzhao** [comment]
新版本已经增加了连击功能，请查看 https://github.com/murphyzhao/FlexibleButton/releases/tag/2.0.0
